# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/04cdcfee-4ef1-4286-958f-068d1931afd3";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2BC2-423D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e24016bd-7adf-4c8e-b840-99366405847b";
      fsType = "btrfs";
    };

  fileSystems."/home/sithy/SteamLibraries/nvme" = {
    device = "/dev/disk/by-uuid/ba1f6618-7d2f-43b6-9ffe-c9f8b728b371";
    fsType = "ext4";
    options = [ "defaults" "nofail" ];
  };

  fileSystems."/home/sithy/SteamLibraries/ssd" = {
    device = "/dev/disk/by-uuid/a45be90d-5e0e-424a-9c06-d2d3d608d91c";
    fsType = "ext4";
    options = [ "defaults" "nofail" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
